### ISSUE TITLE
v1.0.7 is breaking things

### ISSUE THREAD

**Issue by Xowap** [angular-dragdrop/angular-dragdrop#120]
Version 1.0.7 comes with a lot of breaking changes, especially by requiring a new version of Angular. Semver would require at least this version to be 1.1.0 instead. Thanks.

**Comment by BrunoCartier** [comment]
+1.

When using `angular-native-dragdrop#~1.0.6` as a dependency, i.e "*this lib, with version >= 1.0.6 and version < 1.1*", with your recent changes, all stuff related to angular-dragdrop breaks... That's not cool for people using your lib in production ^^'

Sadly, it's to late to fix this correctly, but we hope you will take this into account in the future.

**Comment by Toilal** [comment]
What is really breaking ? The new angular version is not "required", it should work with previous version, it's only recommanded.

**Comment by Xowap** [comment]
In our case it broke (silently, no errors)

**Comment by BrunoCartier** [comment]
You seem to be right, our issue does not come from Angular version changing. One possible cause is:

We need to use a function to determine if an element is draggable or not. So, in 1.0.6, we had to use `ui-draggable="(( isDraggable() ))"`, since `attrs.$observe` was used in your directive. In 1.0.7, `scope.$watch(attrs.uiDraggable, func)` is used, which is an important change.

Anyway, to talk again about this Angular version, since your code works with Angular 1.2, why does your bower.json say your lib is **dependent** from 1.3?

**Comment by Toilal** [comment]
1) As I didn't test on angular 1.2, I don't know. I only know it works on 1.3, but feel free to use it with angular 1.2.

2) For the `attrs.$observe` to `scope.$watch` change in ui-draggable, you are right, it's a breaking change. But it as always been documented to be an Evaluation expression in the docs, so this change was only to match the docs.

> ui-draggable : Expression that should be evaluated. The given expression should resolve to true or false.

 But it would have been better to be bump to next minor version, agree. Just use `ui-draggable="isDraggable()"` now.

**Comment by ganarajpr** [comment]
I have retagged it as 1.1.0. Removed 1.0.7 and 1.0.8. Does that fix the problem ?

**Comment by BrunoCartier** [comment]
Nice, thanks :+1: 
Keep up the good work.

**Comment by Xowap** [comment]
Great :+1:
